### ISSUE TITLE
issue2

### ISSUE THREAD

**Issue by baiyueheiyu** [jcyrss1/baiyuetong.github.io#2]
![image](https://user-images.githubusercontent.com/36462795/36413121-fa945c26-1657-11e8-8c9c-33c5ea6fad75.png)

![image](https://user-images.githubusercontent.com/36462795/36407454-bc67e710-1639-11e8-8b65-3a7abbf02a8c.png)

![image](https://user-images.githubusercontent.com/36462795/36407419-72b5c682-1639-11e8-9d62-ddb1ba749fb9.png)

![image](https://user-images.githubusercontent.com/36462795/36407291-4e47e15a-1638-11e8-916a-478f3a9a1477.png)

![image](https://user-images.githubusercontent.com/36462795/36407230-c700aea2-1637-11e8-89a9-bd754be563f3.png)

![image](https://user-images.githubusercontent.com/36462795/36406714-b4485264-1633-11e8-9cff-21340e5328ff.png)

![image](https://user-images.githubusercontent.com/36462795/36406696-9a4c5f04-1633-11e8-9e96-d2c2edcf4fe5.png)

![image](https://user-images.githubusercontent.com/36462795/36406607-146d4542-1633-11e8-9b94-4e0451588c03.png)

![image](https://user-images.githubusercontent.com/36462795/36406563-c5af3fe6-1632-11e8-9807-4464513f5faa.png)

![image](https://user-images.githubusercontent.com/36462795/36383834-5d7bc92c-15c8-11e8-8821-da79d117d45c.png)

![image](https://user-images.githubusercontent.com/36462795/36384230-8b355fda-15c9-11e8-9365-53ea280b1510.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/36415352-8bf618be-1660-11e8-8d82-10286e504cb4.png)

![image](https://user-images.githubusercontent.com/36257654/36415564-58d9deb0-1661-11e8-95a1-71cffa4c6b15.png)

![image](https://user-images.githubusercontent.com/36257654/36415727-dd0d12b0-1661-11e8-8742-04e9d9b141da.png)


![image](https://user-images.githubusercontent.com/36257654/36415860-4e3c2ae8-1662-11e8-9027-da2cb7af83f9.png)

![image](https://user-images.githubusercontent.com/36257654/36415954-a7e67012-1662-11e8-8e4c-c58793b819b3.png)

![image](https://user-images.githubusercontent.com/36257654/36416102-09adaa2c-1663-11e8-952b-75b1912624aa.png)

![image](https://user-images.githubusercontent.com/36257654/36416154-3043065a-1663-11e8-8ee6-4efaf01947b0.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/36417077-e7c80698-1665-11e8-9b0d-fcc33fa1e34a.png)

![image](https://user-images.githubusercontent.com/36257654/36417171-279888a6-1666-11e8-9223-7e881436f804.png)

![image](https://user-images.githubusercontent.com/36257654/36417279-720f5b58-1666-11e8-9d18-a804ddcfc40d.png)

![image](https://user-images.githubusercontent.com/36257654/36431042-83c06ad8-1691-11e8-9e1a-c556bddd73c8.png)

![image](https://user-images.githubusercontent.com/36257654/36431702-384dabae-1693-11e8-8990-5f214b811bcc.png)


![image](https://user-images.githubusercontent.com/36257654/36432331-e88b874c-1694-11e8-96fa-b849dc7b90d6.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/36433068-a3de735a-1696-11e8-8539-da2b5acc4d13.png)

![image](https://user-images.githubusercontent.com/36257654/36433169-da3aff54-1696-11e8-973f-c7c7f76636f8.png)

![image](https://user-images.githubusercontent.com/36257654/36433328-34fb23ba-1697-11e8-9cad-1f8a7722f200.png)

![image](https://user-images.githubusercontent.com/36257654/36433476-901a2f16-1697-11e8-992a-6d889849b6ce.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/36479785-e53dc4a0-1744-11e8-80c4-63b0f0903fcd.png)

![image](https://user-images.githubusercontent.com/36257654/36480858-c2095112-1748-11e8-8846-8ff554b21d52.png)


![image](https://user-images.githubusercontent.com/36257654/36480925-0ba8efb2-1749-11e8-886c-205cfd56cf9f.png)


![image](https://user-images.githubusercontent.com/36257654/36484936-c42b92e0-1755-11e8-825f-778fb6244f7a.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/37151636-49e02664-2311-11e8-90af-944325bcb6c6.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002426-d537b900-6bf1-11e9-974e-227f44c71355.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002473-3a8baa00-6bf2-11e9-8b79-314d19b7a582.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002570-ef25cb80-6bf2-11e9-9a82-5311f8f754c6.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002580-095fa980-6bf3-11e9-872d-05643bc6d78a.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002608-357b2a80-6bf3-11e9-9d16-140b5ba5ac13.png)

**Comment by jcyrss1** [comment]
![image](https://user-images.githubusercontent.com/36257654/57002619-4c218180-6bf3-11e9-8da7-e253a3a9960e.png)

**Comment by jcyrss1** [comment]
![Uploading image.png…]()
